# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..3).each do |i|

    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos/7"
      host1 = "888#{i}".to_i
      host2 = "889#{i}".to_i
      # 将虚拟机的80端口映射到主机的8888端口
      node.vm.network "forwarded_port", guest: 80, host: host1  
      node.vm.network "forwarded_port", guest: 8888, host: host2

      node.vm.synced_folder "K:/upan/Docker学习笔记/源码", "/home/vagrant/dockercode",
    　　　　type: "smb",
    # 　　　　smb_host: "192.168.33.1",
    　　　　smb_username: "vagrant",
    　　　　smb_password: "vagrant",
    　　　　mount_options: ["username=vagrant","password=vagrant"]

      # 设置私有ip  
      node.vm.network "private_network", ip: "192.168.50.#{i}",auto_config:true

      # 共有ip
      # config.vm.network "public_network"
      # 虚拟机主机名
      node.vm.hostname = "wgw#{i}"

      node.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        # vb.gui = true
        # 给虚拟机命名
        vb.name = "centos_wgw#{i}"
      end
      config.vm.provision "shell", privileged: true, path: "K:/morevirtualmechine/setup.sh"
    end
  end
end
